#!/bin/bash

echo "[*] Stopping the PoshC2 server Docker container..."
CONTAINER=`sudo docker ps -q -f label=posh-server -f ancestor=m0rv4i/poshc2`
if [ ! -z "$CONTAINER" ]; then
    sudo docker stop "$CONTAINER" >/dev/null
    echo "[+] Done"
else
    echo "[*] No running PoshC2 server containers found"
fi