#!/bin/bash

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
    popd >/dev/null
    exit
}

if [ "$1" == "-n" ]; then

    if [ -z "$2" ]; then
        echo "[*] Usage: posh-project -n <new-project-name>"
        exit 1
    fi

    if [ -d "$HOME/.poshc2/$2" ]; then
        echo "[-] Project directory already exists: $HOME/.poshc2/$2"
        exit 1
    fi

    sudo mkdir -p "$HOME/.poshc2/$2"
    echo "$2" | sudo tee "$HOME/.poshc2/CURRENT_PROJECT" >/dev/null
    sudo cp "$HOME/.poshc2/config-template.yml" "$HOME/.poshc2/$2/config.yml"
    echo "[+] Created Project: $2"
    echo "[*] Now run posh-config to set your configuration"

elif [ "$1" == "-s" ]; then
    if [ -z "$2"]; then
        echo "[*] Usage: posh-project -s <project-to-switch-to>"
        exit 1
    fi

    if [ ! -d "$HOME/.poshc2/$2" ]; then
        echo "[-] Project directory does not exist: $HOME/.poshc2/$2"
        exit 1
    fi
    echo "$2" | sudo tee $HOME/.poshc2/CURRENT_PROJECT >/dev/null
    echo "[+] Switched to: $2"
    echo "[*] Restart the PoshC2 C2 server & ImplantHandler to use the new project."

elif [ "$1" == "-l" ]; then

    if [ ! -d "$POSH_PROJECTS_DIR" ]; then
        echo "[-] Project directory does not exist: $POSH_PROJECTS_DIR"
        exit 1
    fi

    echo "[*] Listing PoshC2 Projects in $POSH_PROJECTS_DIR"
    command ls -dl /var/poshc2/*/ 2>/dev/null | cut -d '/' -f 4

else
    echo "[*] Usage: posh-project -n <new-project-name>"
    echo "[*] Usage: posh-project -s <project-to-switch-to>"
    echo "[*] Usage: posh-project -l (lists projects)"
fi
